//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Fail
    {
        public int id { get; set; }
        public int account_id { get; set; }
        public int account_contact { get; set; }
    }
}
